name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

  jobs:
  run-stuff:
    runs-on: ubuntu-latest
    steps:
     - run: echo "Hello world!"
  
